In [ ]:
import sqlite3

In [ ]:
import pandas as pd

df = pd.read_csv('hasil_segmentasi_nasabah.csv')
display(df.head())

,ID_Transaksi,Jumlah_Transaksi,Jenis_Transaksi,Lokasi,Kanal_Transaksi,Usia_Nasabah,Pekerjaan_Nasabah,Durasi_Transaksi,Saldo_Akun,Jumlah_Transaksi_Log,Kluster,Nama_Segmen
0,TX000001,14.09,Debit,San Diego,ATM,70.0,Doctor,81.0,5112.21,2.714032,1,C1 - Saver
1,TX000002,376.24,Debit,Houston,ATM,68.0,Doctor,141.0,13758.91,5.932882,1,C1 - Saver
2,TX000003,126.29,Debit,Mesa,Online,19.0,Student,56.0,1122.35,4.846468,2,C2- Young & Active
3,TX000004,184.50,Debit,Raleigh,Online,26.0,Student,25.0,8569.06,5.223055,2,C2- Young & Active
4,TX000006,92.15,Debit,Oklahoma City,ATM,18.0,Student,172.0,781.68,4.534211,2,C2- Young & Active

In [ ]:
koneksi = sqlite3.connect('database_nasabah.db')
df.to_sql('tabel_nasabah', koneksi, if_exists='replace', index=False)

2283

In [ ]:
koneksi = sqlite3.connect('database_nasabah.db')
query = "SELECT * FROM tabel_nasabah"
df_1 = pd.read_sql(query, koneksi)
koneksi.close()

print("--- Ringkasan Angka (Numerik) ---")
display(df_1.describe())

print("\n--- Ringkasan Kategori (Teks) ---")
display(df_1.describe(include=['object']))

--- Ringkasan Angka (Numerik) ---

,Jumlah_Transaksi,Usia_Nasabah,Durasi_Transaksi,Saldo_Akun,Jumlah_Transaksi_Log,Kluster
count,2283.000000,2283.000000,2283.000000,2283.000000,2283.000000,2283.000000
mean,297.913215,44.547087,119.783180,5095.397858,5.152022,1.217696
std,289.934691,17.856494,70.513242,3910.307331,1.209853,0.663564
min,0.260000,18.000000,10.000000,102.200000,0.231112,0.000000
25%,81.760000,27.000000,63.000000,1484.535000,4.415940,1.000000
50%,213.330000,45.000000,112.000000,4693.600000,5.367517,1.000000
75%,414.630000,59.000000,162.000000,7689.080000,6.029795,2.000000
max,1831.020000,80.000000,300.000000,14977.990000,7.513174,2.000000

--- Ringkasan Kategori (Teks) ---

C:\Users\ASUS\AppData\Local\Temp\ipykernel_32124\3232003737.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df_1.describe(include=['object']))

,ID_Transaksi,Jenis_Transaksi,Lokasi,Kanal_Transaksi,Pekerjaan_Nasabah,Nama_Segmen
count,2283,2283,2283,2283,2283,2283
unique,2283,2,43,3,4,3
top,TX000001,Debit,Fort Worth,Branch,Student,C1 - Saver
freq,1,1767,68,792,605,1170